# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: gel-gwas-1.0dev
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - jupytext
  - r-base
  - r-irkernel
  - r-snakecase
  - r-qqman
  - r-devtools
  - r-rmarkdown
  - r-ggplot2
  - r-plyr
  - r-dplyr
  - r-purrr
  - r-kableextra
  - r-stringr
  - r-dt
  - r-magrittr
  - r-htmltools
  - cairo
  - bioconda::plink
  - bioconductor-biobase
  - bioconductor-gwascat
  - bioconductor-gwastools
  - fonts-anaconda=1
  - r-data.table
  - r-ggpubr
  - r-tidyverse