name: tests for lifebit-ai/gel-gwas
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  test_binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Binary GWAS tests
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_binary
  test_qt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Quantitative trait GWAS
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_qt