name: lintr
on: [push, pull_request]
jobs:
  linux:
    if: contains(github.event.head_commit.message, '[lint skip]') == false
    strategy:
      matrix:
        r: [18.04]
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:${{ matrix.r }}
    steps:
    - uses: actions/checkout@v2
    - name: Install apt-get dependencies
      run: |
        apt-get update
        apt-get install git ssh curl bzip2 -y
    - name: Install lintr
      run: |
        Rscript -e "install.packages('lintr', repos = 'https://cloud.r-project.org')"
      shell:
        bash
    - name: Running lintr
      run: |
        Rscript -e "lintr::lint_dir('./bin/')"
      shell:
        bash
